// actions/flightActions.js

export const GET_FLIGHTS_REQUEST = 'GET_FLIGHTS_REQUEST';
export const GET_FLIGHTS_SUCCESS = 'GET_FLIGHTS_SUCCESS';
export const GET_FLIGHTS_FAILURE = 'GET_FLIGHTS_FAILURE';

